# CMake generated Testfile for 
# Source directory: /media/mrjackspade/4TB/llama.cpp/tests
# Build directory: /media/mrjackspade/4TB/llama.cpp/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test-tokenizer-0-llama-spm "/media/mrjackspade/4TB/llama.cpp/bin/test-tokenizer-0" "/media/mrjackspade/4TB/llama.cpp/tests/../models/ggml-vocab-llama-spm.gguf")
set_tests_properties(test-tokenizer-0-llama-spm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;22;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;73;llama_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-llama-bpe "/media/mrjackspade/4TB/llama.cpp/bin/test-tokenizer-0" "/media/mrjackspade/4TB/llama.cpp/tests/../models/ggml-vocab-llama-bpe.gguf")
set_tests_properties(test-tokenizer-0-llama-bpe PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;22;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;74;llama_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-phi-3 "/media/mrjackspade/4TB/llama.cpp/bin/test-tokenizer-0" "/media/mrjackspade/4TB/llama.cpp/tests/../models/ggml-vocab-phi-3.gguf")
set_tests_properties(test-tokenizer-0-phi-3 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;22;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;75;llama_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-falcon "/media/mrjackspade/4TB/llama.cpp/bin/test-tokenizer-0" "/media/mrjackspade/4TB/llama.cpp/tests/../models/ggml-vocab-falcon.gguf")
set_tests_properties(test-tokenizer-0-falcon PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;22;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;76;llama_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-bert-bge "/media/mrjackspade/4TB/llama.cpp/bin/test-tokenizer-0" "/media/mrjackspade/4TB/llama.cpp/tests/../models/ggml-vocab-bert-bge.gguf")
set_tests_properties(test-tokenizer-0-bert-bge PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;22;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;77;llama_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-starcoder "/media/mrjackspade/4TB/llama.cpp/bin/test-tokenizer-0" "/media/mrjackspade/4TB/llama.cpp/tests/../models/ggml-vocab-starcoder.gguf")
set_tests_properties(test-tokenizer-0-starcoder PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;22;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;83;llama_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-gpt-2 "/media/mrjackspade/4TB/llama.cpp/bin/test-tokenizer-0" "/media/mrjackspade/4TB/llama.cpp/tests/../models/ggml-vocab-gpt-2.gguf")
set_tests_properties(test-tokenizer-0-gpt-2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;22;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;84;llama_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-refact "/media/mrjackspade/4TB/llama.cpp/bin/test-tokenizer-0" "/media/mrjackspade/4TB/llama.cpp/tests/../models/ggml-vocab-refact.gguf")
set_tests_properties(test-tokenizer-0-refact PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;22;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;85;llama_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-command-r "/media/mrjackspade/4TB/llama.cpp/bin/test-tokenizer-0" "/media/mrjackspade/4TB/llama.cpp/tests/../models/ggml-vocab-command-r.gguf")
set_tests_properties(test-tokenizer-0-command-r PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;22;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;86;llama_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-qwen2 "/media/mrjackspade/4TB/llama.cpp/bin/test-tokenizer-0" "/media/mrjackspade/4TB/llama.cpp/tests/../models/ggml-vocab-qwen2.gguf")
set_tests_properties(test-tokenizer-0-qwen2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;22;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;87;llama_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-1-llama-spm "/media/mrjackspade/4TB/llama.cpp/bin/test-tokenizer-1-spm" "/media/mrjackspade/4TB/llama.cpp/tests/../models/ggml-vocab-llama-spm.gguf")
set_tests_properties(test-tokenizer-1-llama-spm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;22;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;111;llama_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-quantize-fns "/media/mrjackspade/4TB/llama.cpp/bin/test-quantize-fns")
set_tests_properties(test-quantize-fns PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;59;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;115;llama_target_and_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-quantize-perf "/media/mrjackspade/4TB/llama.cpp/bin/test-quantize-perf")
set_tests_properties(test-quantize-perf PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;59;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;116;llama_target_and_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-sampling "/media/mrjackspade/4TB/llama.cpp/bin/test-sampling")
set_tests_properties(test-sampling PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;59;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;117;llama_target_and_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-chat-template "/media/mrjackspade/4TB/llama.cpp/bin/test-chat-template")
set_tests_properties(test-chat-template PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;59;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;118;llama_target_and_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-grammar-parser "/media/mrjackspade/4TB/llama.cpp/bin/test-grammar-parser")
set_tests_properties(test-grammar-parser PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;59;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;120;llama_target_and_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-llama-grammar "/media/mrjackspade/4TB/llama.cpp/bin/test-llama-grammar")
set_tests_properties(test-llama-grammar PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;59;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;121;llama_target_and_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-grammar-integration "/media/mrjackspade/4TB/llama.cpp/bin/test-grammar-integration")
set_tests_properties(test-grammar-integration PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;59;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;122;llama_target_and_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-grad0 "/media/mrjackspade/4TB/llama.cpp/bin/test-grad0")
set_tests_properties(test-grad0 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;59;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;123;llama_target_and_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-backend-ops "/media/mrjackspade/4TB/llama.cpp/bin/test-backend-ops")
set_tests_properties(test-backend-ops PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;59;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;125;llama_target_and_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-rope "/media/mrjackspade/4TB/llama.cpp/bin/test-rope")
set_tests_properties(test-rope PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;59;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;127;llama_target_and_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-model-load-cancel "/media/mrjackspade/4TB/llama.cpp/bin/test-model-load-cancel")
set_tests_properties(test-model-load-cancel PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;59;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;129;llama_target_and_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-autorelease "/media/mrjackspade/4TB/llama.cpp/bin/test-autorelease")
set_tests_properties(test-autorelease PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;59;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;130;llama_target_and_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-json-schema-to-grammar "/media/mrjackspade/4TB/llama.cpp/bin/test-json-schema-to-grammar")
set_tests_properties(test-json-schema-to-grammar PROPERTIES  LABELS "main" WORKING_DIRECTORY "/media/mrjackspade/4TB/llama.cpp/tests/.." _BACKTRACE_TRIPLES "/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;59;add_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;134;llama_target_and_test;/media/mrjackspade/4TB/llama.cpp/tests/CMakeLists.txt;0;")
